---
kind: pipeline
type: docker
name: default

steps:
- name: BRANCH SECRETS
  image: node
  environment: 
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
  - echo $USERNAME
  - echo $PASSWORD